version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lofree-backend
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - lofree-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0.36
    container_name: lofree-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lofree
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lofree-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: lofree-pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - lofree-network

volumes:
  db-data:

networks:
  lofree-network:
    driver: bridge
